const express = require('express');
const crypto = require('crypto');
const { query } = require('../db');
const { signId, getClientIp, truncateIp, sessionFingerprint } = require('./track');

const router = express.Router();

// Helper: hash an email address with HMAC (never store raw email)
function hashEmail(email) {
  return crypto
    .createHmac('sha256', process.env.EMAIL_HASH_SECRET)
    .update(email.toLowerCase().trim())
    .digest('hex');
}

// Helper: validate UUID format
function isUUID(str) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(str);
}

// ============================================================
// POST /api/email
// Called by the content script before sending a tracked email.
// Registers the email and all its links. Returns signed tracking IDs.
//
// Body: {
//   subject: string,
//   to: string[],          -- raw email addresses (hashed server-side)
//   cc: string[],          -- raw email addresses (hashed server-side)
//   links: [{ id: uuid, url: string }]  -- UUIDs generated by content script
// }
//
// Returns: {
//   trackingId: string,           -- signed email tracking ID for pixel URL
//   signedEmailId: string,        -- same, alias
//   links: [{ id: uuid, signedId: string }]  -- signed link IDs for href rewriting
// }
// ============================================================

router.post('/email', async (req, res) => {
  try {
    const { subject, to = [], cc = [], links = [] } = req.body;

    if (!subject || typeof subject !== 'string') {
      return res.status(400).json({ error: 'subject required' });
    }

    // Validate link IDs — must all be valid UUIDs
    for (const link of links) {
      if (!link.id || !isUUID(link.id)) {
        return res.status(400).json({ error: 'Invalid link ID format' });
      }
      if (!link.url || typeof link.url !== 'string') {
        return res.status(400).json({ error: 'Link URL required' });
      }
      // Reject non-HTTP(S) URLs
      if (!/^https?:\/\//i.test(link.url)) {
        return res.status(400).json({ error: 'Only http/https URLs allowed' });
      }
    }

    // Check opt-out list for all recipients
    const allEmails = [...to, ...cc].filter(Boolean);
    const recipientHashes = allEmails.map(hashEmail);

    const optOutCheck = recipientHashes.length > 0
      ? await query(
          'SELECT email_hash FROM opt_outs WHERE email_hash = ANY($1)',
          [recipientHashes]
        )
      : { rows: [] };

    const optedOutHashes = new Set(optOutCheck.rows.map(r => r.email_hash));
    const activeHashes = recipientHashes.filter(h => !optedOutHashes.has(h));

    // Capture sender identity so the tracking route can filter out compose-window pixel loads.
    // Storing both IP prefix and fingerprint (IP + User-Agent) means a recipient on the same
    // network is still counted — their email client has a different User-Agent.
    const senderIp = getClientIp(req);
    const senderIpPrefix = truncateIp(senderIp);
    const senderFingerprint = sessionFingerprint(senderIp, req.headers['user-agent'] || '');

    // Insert email record
    const emailResult = await query(
      `INSERT INTO tracked_emails (subject, recipient_hashes, sender_ip_prefix, sender_fingerprint)
       VALUES ($1, $2, $3, $4)
       RETURNING id, tracking_id`,
      [subject.slice(0, 500), activeHashes, senderIpPrefix, senderFingerprint]
    );

    const { id: emailId, tracking_id: emailTrackingId } = emailResult.rows[0];

    // Insert all links
    const signedLinks = [];
    for (const link of links) {
      await query(
        `INSERT INTO tracked_links (link_id, email_id, original_url)
         VALUES ($1, $2, $3)
         ON CONFLICT (link_id) DO NOTHING`,
        [link.id, emailId, link.url.slice(0, 2000)]
      );
      signedLinks.push({ id: link.id, signedId: signId(link.id) });
    }

    res.json({
      trackingId: signId(emailTrackingId),
      signedEmailId: signId(emailTrackingId),
      links: signedLinks,
      optedOutCount: recipientHashes.length - activeHashes.length
    });

  } catch (err) {
    console.error('POST /api/email error:', err.message);
    res.status(500).json({ error: 'Failed to register email' });
  }
});

// ============================================================
// GET /api/emails
// Returns all tracked emails with their event summaries.
// Called by the popup every 30 seconds via the service worker.
// ============================================================

router.get('/emails', async (req, res) => {
  try {
    const result = await query(
      `SELECT
         te.id,
         te.tracking_id,
         te.subject,
         te.sent_at,
         COALESCE(
           json_agg(
             DISTINCT jsonb_build_object(
               'id', e.id,
               'type', e.event_type,
               'occurred_at', e.occurred_at,
               'is_forward', e.is_forward,
               'fingerprint', e.session_fingerprint,
               'user_agent', e.user_agent,
               'link_id', e.link_id
             )
           ) FILTER (WHERE e.id IS NOT NULL),
           '[]'
         ) AS events,
         COALESCE(
           json_agg(
             DISTINCT jsonb_build_object(
               'id', tl.link_id,
               'url', tl.original_url
             )
           ) FILTER (WHERE tl.id IS NOT NULL),
           '[]'
         ) AS links
       FROM tracked_emails te
       LEFT JOIN events e ON e.email_tracking_id = te.tracking_id
       LEFT JOIN tracked_links tl ON tl.email_id = te.id
       GROUP BY te.id, te.tracking_id, te.subject, te.sent_at
       ORDER BY te.sent_at DESC
       LIMIT 100`,
      []
    );

    res.json({ emails: result.rows });
  } catch (err) {
    console.error('GET /api/emails error:', err.message);
    res.status(500).json({ error: 'Failed to fetch emails' });
  }
});

// ============================================================
// POST /api/optout
// Adds an email hash to the opt-out list.
// Called from the opt-out page when a recipient clicks "Opt out".
// trackingId in body is the email-level tracking UUID (not signed).
// ============================================================

router.post('/optout', async (req, res) => {
  try {
    const { trackingId, emailHash } = req.body;

    if (emailHash && typeof emailHash === 'string') {
      await query(
        'INSERT INTO opt_outs (email_hash) VALUES ($1) ON CONFLICT DO NOTHING',
        [emailHash.slice(0, 64)]
      );
    } else if (trackingId && typeof trackingId === 'string') {
      // If we received the email tracking ID instead, just acknowledge
      // (We don't have the raw email, so we can't hash it here — the content
      //  script would need to pass the email hash directly for this to be useful)
      // For now, just return success
    }

    res.json({ success: true });
  } catch (err) {
    console.error('POST /api/optout error:', err.message);
    res.status(500).json({ error: 'Failed to opt out' });
  }
});

module.exports = router;
